# Generated by Django 5.0.1 on 2025-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recycle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="cost_saved",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="recycling_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
