# Generated by Django 5.0.1 on 2025-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recycle", "0002_uploadedfile_cost_saved_uploadedfile_item_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="weight",
            new_name="item_weight",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="item_composition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="item_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="recycling_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
