# Generated by Django 5.0.1 on 2025-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recycle", "0003_rename_weight_uploadedfile_item_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="recycling_center_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
