# Generated by Django 5.0.1 on 2025-05-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recycle", "0004_uploadedfile_recycling_center_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimilarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similar_item_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_items",
                        to="recycle.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
