# Generated by Django 5.0.1 on 2025-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recycle", "0005_similaritem"),
    ]

    operations = [
        migrations.AddField(
            model_name="similaritem",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="similaritem",
            name="item_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        
        migrations.RemoveField(
            model_name="similaritem",
            name="uploaded_file",
        ),
        migrations.AddIndex(
            model_name="similaritem",
            index=models.Index(
                fields=["item_name"], name="recycle_sim_item_na_cf5950_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="similaritem",
            unique_together={("item_name", "similar_item_name")},
        ),
    ]
